Add codec parameters type for subtitles.
angelcam/rust-ac-ffmpeg pull request #13
Opened 2020-10-23 00:28 UTC by xaep

Mainly this is to allow remuxing subtitles (as right now there's no way to specify a subtitle codec for a stream), i.e. take a .mkv with srt subtitle track and split it into a separate webvtt file.

I did not add a builder for subtitle params as it seemed excessive given that there's only one parameter - codec name.

2020-10-23 09:42 UTC, operutka requested changes
Good job! Thank you for your contribution. I have only a small question regarding the `extradata()` method. See below.

2020-10-23 09:42 UTC, operutka commented on src/codec/mod.rs
> +    pub fn extradata(&self) -> Option<&[u8]> {
I'm not sure if extradata is used in combination with subtitle codecs. Anyway, if we allow access to extradata here, we should also allow setting the extradata in a builder. (Or we can remove this method.)

2020-10-24 01:22 UTC, xaep commented on src/codec/mod.rs
> +    pub fn extradata(&self) -> Option<&[u8]> {
It's an artifact of copy-paste, removed it as I don't know if extradata has any use for subtitles at all.

2020-10-26 08:02 UTC, operutka approved these changes
Perfect!

2020-10-26 08:02 UTC, merged