Allow setting stream metadata from safe rust
angelcam/rust-ac-ffmpeg pull request #20
Opened 2021-03-20 21:37 UTC by tnibler

This patch allows specifying metadata options to be applied to an `AVStream` after it's created.

2021-03-20 21:45 UTC, tnibler commented
I also think it would be nice to return the index of the created stream in `add_stream` like here: https://github.com/tnibler/rust-ac-ffmpeg/commit/c1d9c76c8d0448223f8ab14e2557f00924d8c39d. Should I add it to this PR or would you prefer keeping the 2 changes separate?

2021-03-22 09:11 UTC, operutka requested changes
Thank you for the PR! I'm glad we can fill in another gap in the API here. If you don't mind, I'd prefer a few changes in order to remain consistent with the rest of the API:

1. As you proposed, the `MuxerBuilder::add_stream()` method should return the stream index.
2. Other than that, I would keep the method signature as it was. I wouldn't add the metadata argument here.
3. Instead, I'd add a method named `set_stream_option` with the following signature:

    ```rust
    /// Set a stream option.
    ///
    /// # Panics
    /// The method panics if there is no stream with a given index.
    pub fn set_stream_option<V>(self, stream_index: usize, name: &str, value: V) -> MuxerBuilder
    where
        V: ToString,
    {
        ...
    }
    ```

4. And finally, I wouldn't try to reflect the ffmpeg option types here. Setting stream options as strings should be fine. The ffmpeg can handle the necessary parsing/type conversions. The `MuxerBuilder::set_option()` method also sets all options as strings and it can be used for setting string options, integer options, flags, ... I know it's a bit inefficient but it simplifies the API quite a bit. And a muxer is usually constructed only once, so it shouldn't be a big problem. Note that the method signature allows calling the method like this:

    ```rust
    builder.set_stream_option(0, "rotate", 90)
    ```

    because all integer types implement `ToString`.

2021-03-23 09:31 UTC, operutka requested changes
It looks good. There is only one minor issue (see below) and one question - have you tested that the metadata options are freed when the muxer gets dropped? I'm not sure if it's done automatically by de-allocating `AVFormatContext` or if it needs to be done explicitly.

2021-03-23 09:31 UTC, operutka commented on src/format/muxer.rs
> +            ffw_muxer_set_stream_option(self.ptr, stream_index, key.as_ptr(), value.as_ptr());
You should also check the return value and panic if it's negative (the same way as it's done in the `set_option()` method).

2021-03-23 09:40 UTC, tnibler commented on src/format/muxer.rs
> +            ffw_muxer_set_stream_option(self.ptr, stream_index, key.as_ptr(), value.as_ptr());
Good point about the freeing question, I'll have a look.

2021-03-23 09:48 UTC, tnibler commented on src/format/muxer.rs
> +            ffw_muxer_set_stream_option(self.ptr, stream_index, key.as_ptr(), value.as_ptr());
Yes, it's all freed automatically :)

https://github.com/FFmpeg/FFmpeg/blob/84b02bbb78b5aaec0a9de1d0859c4cf7f339a564/libavformat/utils.c#L4404

2021-03-23 15:55 UTC, operutka commented on src/format/muxer.rs
> +            ffw_muxer_set_stream_option(self.ptr, stream_index, key.as_ptr(), value.as_ptr());
Good. No more questions/comments from me.

2021-03-23 15:56 UTC, operutka approved these changes

2021-03-23 15:57 UTC, operutka commented
I'll include it in the next release.

2021-03-23 15:57 UTC, merged