Add initial implementation for Stream type
angelcam/rust-ac-ffmpeg pull request #21
Opened 2021-03-21 15:50 UTC by kicsyromy

Initial implementation for Stream type

2021-03-21 15:55 UTC, kicsyromy commented
Hello,

I've set up an initial batch of changes and made this PR to get some feedback if I'm going in the right direction. With that in mind I have 3 questions:
1. Is this new type the right approach?
2. If yes, then what would be the best way to get a stream from the Demuxer, I was thinking something along the lines of how it is done with CodecParameters.
3. It is unclear what the lifetime of an AVStream obtained from an AVFormatContext is, my assumption is that when AVFormatContext is destroyed the AVStream is as well, is this correct?

Thank you

2021-03-22 10:28 UTC, operutka commented
Hi @kicsyromy! Thank you for the PR. I've checked it briefly and I like it. I'll do a detailed code review later this week.

To answer your questions:
1. Yes, I believe it's the right approach.
2. Here I'm not sure yet. We have several options. We could add a method named `streams` with the following signature:

    ```rust
    pub fn streams(&self) -> &[Stream] { ... }
    ```
    
    but the main problem here is that we cannot create a slice of `Stream` types directly from the pointer to the corresponding demuxer. We'd have to create an internal `Vec<Stream>` the same way as it's done with codec parameters at `DemuxerWithCodecParameters` and fill it at some point. I think that this method should be available only on the `DemuxerWithCodecParameters` because, if I remember correctly, the streams are not available until the container headers are processed. I will check it though.
    
    This approach would be good from the lifetime point of view. The returned slice would have the same lifetime as the corresponding demuxer, so we wouldn't have to take any special care here.
    
    The second option would be creating a pair of methods with the following signature:
    
    ```rust
    pub fn get_stream(&self, index: usize) -> Stream<'_> { ... }
    pub fn get_stream_count(&self) -> usize { ... }
    ```
    
    We'd have to capture the lifetime of the demuxer within the returned stream here. Otherwise, the stream could outlive the demuxer. I'm not in favor of this approach mostly because the `get_stream()` method would panic if called with an invalid stream index.
    
    The third option would be having a method with a signature like this:
    
    ```rust
    pub fn streams(&self) -> StreamIter<'_> { ... }
    ```
    
    and the `StreamIter` would be an iterator like:
    
    ```rust
    impl<'a> Iterator for StreamIter<'a> {
        type Item = Stream<'a>;
        
        fn next(&mut self) -> Option<Self::Item> { ... }
    }
    ```
    
    We'd also have to capture the lifetime of the corresponding demuxer here.
    
    I'm not sure yet which option would be the best here. I'm slightly preferring the slice or the iterator. I'll try to think about it. Let me know your opinion.

3. I've partially answered this in the previous point. Yes, your assumption is correct `AVStream` is valid only as long as the corresponding `AVFormatContext` is valid. We cannot allow the `Stream` instances to exist once the corresponding demuxer has been destroyed.

2021-03-22 15:36 UTC, kicsyromy commented
> 
> 
> Hi @kicsyromy! Thank you for the PR. I've checked it briefly and I like it. I'll do a detailed code review later this week.
> 
> To answer your questions:
> 
>     1. Yes, I believe it's the right approach.
> 
>     2. Here I'm not sure yet. We have several options. We could add a method named `streams` with the following signature:
>        ```rust
>        pub fn streams(&self) -> &[Stream] { ... }
>        ```
>        
>        
>        but the main problem here is that we cannot create a slice of `Stream` types directly from the pointer to the corresponding demuxer. We'd have to create an internal `Vec<Stream>` the same way as it's done with codec parameters at `DemuxerWithCodecParameters` and fill it at some point. I think that this method should be available only on the `DemuxerWithCodecParameters` because, if I remember correctly, the streams are not available until the container headers are processed. I will check it though.
>        This approach would be good from the lifetime point of view. The returned slice would have the same lifetime as the corresponding demuxer, so we wouldn't have to take any special care here.
>        The second option would be creating a pair of methods with the following signature:
>        ```rust
>        pub fn get_stream(&self, index: usize) -> Stream<'_> { ... }
>        pub fn get_stream_count(&self) -> usize { ... }
>        ```
>        
>        
>        We'd have to capture the lifetime of the demuxer within the returned stream here. Otherwise, the stream could outlive the demuxer. I'm not in favor of this approach mostly because the `get_stream()` method would panic if called with an invalid stream index.
This was my main concern also, I would need to tie the lifetime of the stream to the Demuxer, which could end up being more complicated than it needs to be.
>        The third option would be having a method with a signature like this:
>        ```rust
>        pub fn streams(&self) -> StreamIter<'_> { ... }
>        ```
>        
>        
>        and the `StreamIter` would be an iterator like:
>        ```rust
>        impl<'a> Iterator for StreamIter<'a> {
>            type Item = Stream<'a>;
>            
>            fn next(&mut self) -> Option<Self::Item> { ... }
>        }
>        ```
>        
>        
>        We'd also have to capture the lifetime of the corresponding demuxer here.
>        I'm not sure yet which option would be the best here. I'm slightly preferring the slice or the iterator. I'll try to think about it. Let me know your opinion.

Honestly while the iterator option looks a bit more rust-ic (pun intended), I think I would prefer not having explicit lifetime semantics on the Demuxer, so I think I will try to go down the route of owned Vec<Stream> and see how how it pans out. 

> 
>     3. I've partially answered this in the previous point. Yes, your assumption is correct `AVStream` is valid only as long as the corresponding `AVFormatContext` is valid. We cannot allow the `Stream` instances to exist once the corresponding demuxer has been destroyed.
Great to get confirmation on this, the docs aren't very explicit on lifetimes of pointers passed around, in this particular instance.

2021-03-23 07:56 UTC, kicsyromy commented
I have an initial implementation for retrieving the Stream from ```DemuxerWithCodecParameters```, and a rough implementation of seeking with very minimal error handling.

I've tested seeking by frame and timestamp on some local files, and seeking by timestamp works (as long as the ```TimeBase``` is consistent) while seeking by frame seems to be broken for the time being.

At some point, when I get close to a form resembling it's final one, I would like to test on multiple types of input, and I'll need some guidance on that part.

I welcome any and all criticism 😄

2021-03-23 09:11 UTC, operutka commented
Great! I think you should focus mainly on the common containers (like mkv, mp4, avi) in your testing and, in addition to those, you should also test the behavior on non-indexed formats intended for streaming (like MPEG-TS). It will be also important to test the seeking with seekable and non-seekable IO for all the formats.

2021-03-30 04:27 UTC, kicsyromy commented
Hi @operutka,

I've pushed a new set of changes and started testing with the formats you mentioned in the previous commit.
I've downloaded some sample files, and tested with some of my ripped BluRay TV shows and movies, and it seems to work OK for all three seek types. Of course there is some variation between seek type, codecs, types of streams, but I would think that is expected.

The only format that consistently does not work is the TS format. I'm not very familiar with this fomat, you mention that it is intended for streaming, does that mean we expect it to **not** be seekable?

Also, regarding seekable and non-seekable IO, could you give me a hint, or an example of what non-seekable IO might be in this case?

Thank you!

2021-03-30 08:44 UTC, operutka commented
> does that mean we expect it to not be seekable?

Yes, that's exactly it. MPEG-TS, fragmented MP4 and other streaming formats are typically non-seekable. They're usually transferred via a non-seekable IO (e.g. as an HTTP body). I'm not sure what's the ffmpeg behavior here when you attempt to seek in these formats. Does it return an error?

> could you give me a hint, or an example of what non-seekable IO might be in this case?

Sure. It's simple. You can create a demuxer using a seekable IO like this:
```rust
use ac_ffmpeg::{
    format::{
        demuxer::{Demuxer, DemuxerWithCodecParameters},
        io::IO,
    },
    Error,
};

fn open_input(path: &str) -> Result<DemuxerWithCodecParameters<File>, Error> {
    let input = File::open(path)
        .map_err(|err| Error::new(format!("unable to open input file {}: {}", path, err)))?;

    let io = IO::from_seekable_read_stream(input);

    Demuxer::builder()
        .build(io)?
        .find_stream_info(None)
        .map_err(|(_, err)| err)
}
```

If you were using a non-seekable IO, the only change would be:
```rust
let io = IO::from_read_stream(input);
```

Of course, for the purpose of testing, you can take a seekable IO (e.g. a file) as a non-seekable IO:
```rust
 let input = File::open(path)
    .map_err(|err| Error::new(format!("unable to open input file {}: {}", path, err)))?;

let io = IO::from_read_stream(input);
```

2021-04-01 16:56 UTC, kicsyromy commented
Sorry about the late reply

> I'm not sure what's the ffmpeg behavior here when you attempt to seek in these formats. Does it return an error?
Nope, it just stays at the first frame, and does nothing. No warnings, no error, no output, just silently does nothing.

The info you provided is great, I'll try and do some testing this weekend and see what else crops up 😄

2021-04-06 16:23 UTC, kicsyromy commented
So after some testing, it looks like independent of the type of IO used seeking works in the exact same way, streams that can be seeked seek regardless of the type of IO and the ones that can't don't . I'm not sure what to make of this.

I'm going to set the PR as ready for review because I'm not sure I want to expand this any further. To me what I have now looks like an OK start and after some clean-up, and review fixes, after merging, we can take it further.

As always I welcome any and all criticism 😄

2021-04-12 11:03 UTC, operutka requested changes
Sorry for the delay. The last week was quite busy and I didn't have much time to do the review. Anyway, great job! I'm really glad we can push this thing forward. I have a few comments. They're mainly about the place where we should put the seek methods plus a few other less important things.

2021-04-14 04:12 UTC, kicsyromy commented on src/stream.c
> +typedef struct Stream {
Right, will do

2021-04-14 04:12 UTC, kicsyromy commented on src/stream.c
> +int ffw_stream_seek_frame(Stream* stream, unsigned stream_index, int64_t timestamp, int seek_by, int seek_target) {
Yes, this makes sense

2021-04-14 04:13 UTC, kicsyromy commented on src/stream.rs
> +pub enum SeekTarget {
Very good point, I like this approach

2021-04-14 04:13 UTC, kicsyromy commented on src/stream.rs
> +    Precise,
Hmm, I'll have to do some more testing then, but you're probably right.

2021-04-14 04:14 UTC, kicsyromy commented on src/stream.rs
> +    pub fn index(&self) -> usize {
I can take it or leave it :)
I'll make both this and the one below non-public then.

2021-04-14 04:16 UTC, kicsyromy commented
Hi @operutka,

No worries on the review, I juggle between different day-to-day tasks as well.
I'll start working on the changes sometime this week and hopefully push them by the end of the week.

Thanks

2021-04-14 08:06 UTC, operutka commented on src/stream.rs
> +    pub fn index(&self) -> usize {
I believe that the index shouldn't be needed at all. I assume that users will know the stream index (or they can easily derive it), because they accessed the stream using the `streams()` method on the corresponding demuxer. Generally, slice items usually don't know their index within the slice. I don't think this case should be any different.

I think we can keep the `id` method for now but I'd hide it using `#[doc(hidden)]`.

2021-04-18 18:27 UTC, kicsyromy commented
Hi,

I've made the modifications you mentioned in your review. I do have one remaining question, I realized that it's not clear to me what the AV_SEEK_* flags do (thought I did until you mentioned that ANY and BACKWARD are not mutually exclusive), so I didn't make any changes, yet, in that regard.

Could you point me to some clear docs that explain these flags a bit better? Everything that I found (including FFMPEG examples) have been overly-complex, to say the least. And looking at stuff like SO and blog posts doesn't really help that much, since they tend to hand-wave them.

Thank you.

2021-04-20 08:35 UTC, operutka commented
The ffmpeg documentation is quite poor. These are all the `AVSEEK_*` related docs I've been able to find:
* http://ffmpeg.org/doxygen/4.1/avformat_8h_source.html#l02420
* http://ffmpeg.org/doxygen/4.1/avformat_8h_source.html#l02490
* http://ffmpeg.org/doxygen/4.1/avformat_8h_source.html#l02818

You could find more info by looking at the implementation of `av_seek_frame()`.

My understanding of the flags is this:
* `AVSEEK_FLAG_BACKWARD` - If set, the seek function will seek to the closest (key)frame with a timestamp <= the given timestamp. Otherwise, the seek function will seek to the closest frame with a timestamp >= the given timestamp (the default behavior).
* `AVSEEK_FLAG_ANY` - The seek function will seek to the closest frame regardless if it's a key-frame.
* `AVSEEK_FLAG_BYTE` - The given position is interpreted as a byte position.
* `AVSEEK_FLAG_FRAME` - The given position is interpreted as a frame number.

I'm also not sure if supporting `AVSEEK_FLAG_FRAME` makes any sense in our case. It definitely isn't implemented by any of the generic seek functions (I've checked the code). It may be implemented by some format-specific seek functions though. But the main point is that the term "frame number" does not make much sense without specifying the stream index because each stream usually has a different number of frames. The implementation even automatically assumes the position is a timestamp if the stream index is `-1` (regardless of the `AVSEEK_FLAG_FRAME` flag), see:
http://ffmpeg.org/doxygen/4.1/libavformat_2utils_8c_source.html#l02462

2021-04-26 11:15 UTC, operutka requested changes
Good job! There is a few more details I'd like to resolve before we merge this but mostly I'm happy with it.

2021-04-26 11:15 UTC, operutka commented on src/format/demuxer.rs
> +    streams: Option<Vec<Stream>>,
Unless you really need this for some use case, I'd remove it. I understand your thinking here. Obviously, you don't want to loose the streams when deconstructing an instance of `DemuxerWithCodecParameters`. But the API looks a bit weird in this case.

I'm playing with a thought to do a breaking change that will move the codec parameters from the demuxer to the streams and I'd also change the `deconstruct()` method to `into_demuxer()`. But, of course, it shouldn't be a part of this PR. I'll do it once this PR is merged.

2021-04-26 11:15 UTC, operutka commented on src/stream.rs
> +    pub(crate) unsafe fn from_format_context(ptr: *mut c_void, stream_index: c_uint) -> Self {
This method can be changed into (see one of my previous comments):
```rust
pub unsafe fn from_raw(ptr: *mut c_void) -> Self {
    ...
}
```

2021-04-26 11:37 UTC, kicsyromy commented
@operutka 
Hi sorry about the radio silence, been a busy few weeks. I'll try and get these latest changes buttoned up sometime by the end of the week.

Thanks

2021-05-07 06:02 UTC, kicsyromy commented
@operutka 

Pushed a new batch of changes as per your findings. Let me know if there is anything else. :)

Thank you

2021-05-14 09:38 UTC, operutka requested changes
Perfect! I'm happy with it. There is only one "typo" I found. Please, fix this last problem and also make sure that you run `cargo fmt` to fix any formatting issues. I'll merge it then.

2021-05-14 09:38 UTC, operutka commented on src/format/demuxer.c
> +AVStream* ffw_demuxer_get_stream(Demuxer* demuxer);
This function declaration does not match the actual definition on line 183. The `stream_index` argument is missing here.

2021-05-14 15:01 UTC, kicsyromy commented on src/format/demuxer.c
> +AVStream* ffw_demuxer_get_stream(Demuxer* demuxer);
Fixed :)

2021-05-14 15:40 UTC, operutka approved these changes

2021-05-14 15:42 UTC, merged

2021-05-14 15:44 UTC, operutka commented
... and merged! Thank you for your contribution. I really appreciate it.

2021-05-14 15:45 UTC, operutka commented
I will try to push forward the idea of moving CodecParameters to the Stream type before I make the next release.

2021-05-14 15:50 UTC, kicsyromy commented
> 
> 
> ... and merged! Thank you for your contribution. I really appreciate it.

Great! Thank you :)
Glad I could help