Implement the Debug trait for TimeBase
angelcam/rust-ac-ffmpeg pull request #31
Opened 2021-09-06 17:24 UTC by dceddia

I wanted to print out some TimeBases for debugging and I got tired of manually pulling out the `num()` and `den()` so I added this :)

2021-09-07 08:50 UTC, operutka requested changes
Thanks for the PR! Please, fix all compilation warnings and Clippy lints in your code and make sure that the code is formatted using `cargo fmt`. Use these commands:
```bash
cargo fmt
cargo build
cargo clippy -- -D warnings
```

Namely there is an issue with unused import:
```text
warning: unused import: `Display`
 --> src/time.rs:5:24
  |
5 |     fmt::{self, Debug, Display, Formatter},
  |                        ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

2021-09-09 00:30 UTC, dceddia commented
Sorry, fixed!

I had implemented Display at first and then switched to Debug to match the other structs. Whoops!

2021-09-09 09:16 UTC, operutka approved these changes

2021-09-09 09:17 UTC, operutka commented
Perfect! Thank you. It'll be included in the next release.

2021-09-09 09:17 UTC, merged