Add the ability to provide a hint to the muxer about the desired timebase
angelcam/rust-ac-ffmpeg pull request #44
Opened 2022-09-16 09:54 UTC by irkill

Hello! I found it useful to have the ability to provide a hint to the muxer about the desired timebase.

This is useful, for example, when transmuxing to MP4 container. If the timebase of the input stream differs from the output, then when transferring the timestamp from one timebase to another due to inaccuracy of calculations, there may be two different packets with the same dts/pts at the output. Which will result in an error message from FFmpeg:
```
[mp4 @ 0x7ff150113f40] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1538093 >= 1538093
```

2022-09-16 14:48 UTC, operutka commented
Hello @irkill and thank you for your pull request! I'm out of my office for the next two weeks. I'll check the PR once I get back.

2022-11-16 14:29 UTC, operutka requested changes
It looks good. There's just one minor issue that I'd like to get fixed. Otherwise, I'm happy with it.

2022-11-16 14:29 UTC, operutka commented on src/format/stream.rs
> +    fn ffw_stream_set_time_base(stream: *const c_void, num: u32, den: u32);
```suggestion
    fn ffw_stream_set_time_base(stream: *mut c_void, num: u32, den: u32);
```

2022-11-18 12:39 UTC, irkill commented on src/format/stream.rs
> +    fn ffw_stream_set_time_base(stream: *const c_void, num: u32, den: u32);
Done.

2022-11-18 16:01 UTC, merged