Expose picture_type for frames
angelcam/rust-ac-ffmpeg pull request #49
Opened 2022-11-17 18:27 UTC by harrynull

This PR exposes `picture_type` to users so they can force an I frame when needed. e.g. streaming apps might want to send an I frame when there is a new user joining so they could start decoding immediately.

Please let me know if I did anything wrong!

2022-11-18 10:42 UTC, operutka requested changes
I'm OK with exposing the picture type API. I'm just curious - where did you find out that it can be used to force an I frame? I haven't found any FFmpeg documentation mentioning this feature.

2022-11-18 10:42 UTC, operutka commented on src/codec/frame.c
> +    frame->pict_type = picture_type;
This could lead to bugs if the picture type numbering changes in future versions of FFmpeg. We should do mapping between our numbering and the FFmpeg numbering.
```c
switch (picture_type) {
    case 1: return AV_PICTURE_TYPE_I;
    case 2: return AV_PICTURE_TYPE_P;
    ...
    default: return AV_PICTURE_TYPE_NONE;
}
```

2022-11-18 10:42 UTC, operutka commented on src/codec/frame.c
> +    return frame->pict_type;
This could lead to bugs if the picture type numbering changes in future versions of FFmpeg. We should do mapping between our numbering and the FFmpeg numbering.
```c
switch (frame->pict_type) {
    case AV_PICTURE_TYPE_I: return 1;
    case AV_PICTURE_TYPE_P: return 2;
    ...
    default: return 0;
}
```

2022-11-18 10:42 UTC, operutka commented on src/codec/video/frame.rs
> +    }
1. I'd make this method available only within the crate itself. Let's not expose the implementation details.
2. I guess the `Option` is redundant here. I'd simply return `PictureType::None` in the undefined cases.
3. This method is being used to get the enum variant from a number returned by the C function. The C function returns `c_int` (which is fine) but here you expect `i32`. Do not confuse these two types. They are not necessarily the same thing on all platforms.
4. I'd name this method `from_raw` to remain consistent with the rest of the crate.

```suggestion
    pub(crate) fn from_raw(value: c_int) -> Self {
        match value {
            1 => PictureType::I,
            2 => PictureType::P,
            3 => PictureType::B,
            4 => PictureType::S,
            5 => PictureType::Si,
            6 => PictureType::Sp,
            7 => PictureType::Bi,
            _ => PictureType::None,
        }
    }
```

2022-11-18 10:42 UTC, operutka commented on src/codec/video/frame.rs
> +        unsafe { ffw_frame_set_picture_type(self.ptr, picture_type as i32) };
Do not confuse `c_int` and `i32`. They are not necessarily the same thing on all platforms.

```suggestion
        unsafe { ffw_frame_set_picture_type(self.ptr, picture_type as c_int) };
```

2022-11-18 15:47 UTC, harrynull commented
Thank you for reviewing. I'll address the comments later today.

> I'm just curious - where did you find out that it can be used to force an I frame?

https://stackoverflow.com/questions/67086742/how-can-i-forcing-current-frame-to-be-encoded-as-intra-frame-using-libavcodec

Also [FFmpeg's documentation](https://ffmpeg.org/doxygen/4.0/structAVFrame.html#af9920fc3fbfa347b8943ae461b50d18b) says there exists such a field, though it didn't provide too much information on it. But it seems from the [source code for x264 encoder](https://ffmpeg.org/doxygen/4.0/libx264_8c_source.html#l00300) suggests that this field is used as such.

2022-11-19 16:44 UTC, operutka requested changes
No major objections. Just code style. Otherwise, I'm happy with the PR.

2022-11-19 16:44 UTC, operutka commented on src/codec/frame.c
> +    return 0; // None
```suggestion
    switch (frame->pict_type) {
        case AV_PICTURE_TYPE_I: return 1;
        case AV_PICTURE_TYPE_P: return 2;
        case AV_PICTURE_TYPE_B: return 3;
        case AV_PICTURE_TYPE_S: return 4;
        case AV_PICTURE_TYPE_SI: return 5;
        case AV_PICTURE_TYPE_SP: return 6;
        case AV_PICTURE_TYPE_BI: return 7;
        default: return 0;
    }
```

2022-11-19 16:44 UTC, operutka commented on src/codec/frame.c
> +    frame->pict_type = type;
```suggestion
    enum AVPictureType type;

    switch(picture_type) {
        case 1: type = AV_PICTURE_TYPE_I; break;
        case 2: type = AV_PICTURE_TYPE_P; break;
        case 3: type = AV_PICTURE_TYPE_B; break;
        case 4: type = AV_PICTURE_TYPE_S; break;
        case 5: type = AV_PICTURE_TYPE_SI; break;
        case 6: type = AV_PICTURE_TYPE_SP; break;
        case 7: type = AV_PICTURE_TYPE_BI; break;
        default: type = AV_PICTURE_TYPE_NONE; break;
    }

    frame->pict_type = type;
```

2022-11-20 11:12 UTC, operutka approved these changes

2022-11-20 11:12 UTC, merged