Add ability to set/get stream id.
angelcam/rust-ac-ffmpeg pull request #50
Opened 2022-11-18 21:26 UTC by Lighty0410

Closed the previous PR due to the incorrect approach. Guess this one should be better.

2022-11-19 16:35 UTC, operutka requested changes
Just one small detail. Otherwise, I'm happy with the PR.

2022-11-19 16:35 UTC, operutka commented on src/format/stream.rs
> +    pub fn get_stream_id(&self) -> i32 {
to be consistent with the other methods:
```suggestion
    pub fn stream_id(&self) -> i32 {
```

2022-11-19 19:13 UTC, Lighty0410 commented on src/format/stream.rs
> +    pub fn get_stream_id(&self) -> i32 {
Done, thanks :)

2022-11-20 11:14 UTC, operutka approved these changes

2022-11-20 11:14 UTC, merged