Expose stream side data
angelcam/rust-ac-ffmpeg pull request #60
Opened 2023-01-18 17:54 UTC by irkill

Hello! I am faced with the following task, there is the video that has side data in one stream:
```bash
$ ffprobe video.mp4
...
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, 3186 kb/s, 30.03 fps, 30 tbr, 19200 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -180.00 degrees

...
```
If you transcode such a video and don't copy the stream side data to the output video, the output video will be rotated relative to the source video.

To properly transcode such a video, we need to be able to copy the stream side data to the output video.

2023-01-19 06:09 UTC, irkill commented
I'm thinking of replacing the function `Stream::side_data` return type from `SideDataIter<'_>` to `&[PacketSideData]`  in this PR. It seems safer this way. What do you think about this?

2023-01-27 15:02 UTC, operutka commented
Thank you again for another PR. Hopefully, I'll get to it sometime next week.

2023-03-19 15:42 UTC, operutka requested changes
Thank you again for the PR. I'd like to make a few changes before merging it. Plus, I'd also like to rename `PacketSideData` to `SideData`, `PacketSideDataRef` to `SideDataRef` and `PacketSideDataType` to `SideDataType`.

2023-03-19 15:42 UTC, operutka commented on src/format/stream.rs
> +}
1. Let's move this into `packet.rs`.
2. Let's change the definition a bit.

We can use a trick with casting the side data pointer directly to `&PacketSideDataRef` here. The type itself has zero size and there will never be an instance of this type, only a reference. It's similar to `std::path::Path`. It'd look like this:
```rust
/// ...
pub struct PacketSideDataRef(());

impl PacketSideDataRef {
    /// ...
    pub(crate) fn from_raw_ptr(ptr: *const c_void) -> &Self {
        unsafe { &*(ptr as *const Self) }
    }

    /// ...
    fn as_ptr(&self) -> *const c_void {
        self as *const Self as _
    }
    
    /// ...
    pub fn data(&self) -> &[u8] {
        unsafe {
            let data = ffw_packet_side_data_get_data(self.as_ptr());
            let len = ffw_packet_side_data_get_size(self.as_ptr());

            std::slice::from_raw_parts(data, len)
        }
    }
    
    /// ...
    pub fn data_type(&self) -> PacketSideDataType {
        let data_type = unsafe { ffw_packet_side_data_get_type(self.as_ptr()) };

        PacketSideDataType::from_raw(data_type)
    }
}
```

The owned type `PacketSideData` would then look like this:
```rust
/// ...
pub struct PacketSideData {
    ptr: *mut c_void,
}

impl PacketSideData {
    /// ...
    pub(crate) unsafe fn from_raw_ptr(ptr: *mut c_void) -> Self {
        Self { ptr }
    }
}

impl Deref for PacketSideData {
    type Target = PacketSideDataRef;

    fn deref(&self) -> &Self::Target {
        PacketSideDataRef::from_raw_ptr(self.ptr)
    }
}
```

However, since `PacketSideData` actually isn't used anywhere, we probably don't need it at all.

The `SideDataIter` definition will then change like this:
```rust
/// ...
pub struct SideDataIter<'a> {
    stream: &'a Stream,
    index: u32,
    len: u32,
}

impl<'a> Iterator for SideDataIter<'a> {
    type Item = &'a PacketSideDataRef;

    fn next(&mut self) -> Option<Self::Item> {
        ...
    }
}
```

This is, in my opinion, a bit more natural.

2023-03-19 15:42 UTC, operutka commented on src/packet.rs
> +    fn ffw_packet_side_data_get_data(side_data: *mut c_void) -> *mut u8;
```suggestion
    fn ffw_packet_side_data_get_data(side_data: *const c_void) -> *const u8;
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.c
> +AVPacketSideData* ffw_stream_get_side_data(const AVStream* stream, unsigned index) {
```suggestion
const AVPacketSideData* ffw_stream_get_side_data(const AVStream* stream, size_t index) {
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.c
> +int ffw_stream_get_nb_side_data(const AVStream* stream) {
```suggestion
size_t ffw_stream_get_nb_side_data(const AVStream* stream) {
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.rs
> +    fn ffw_stream_get_nb_side_data(stream: *const c_void) -> c_uint;
```suggestion
    fn ffw_stream_get_nb_side_data(stream: *const c_void) -> usize;
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.rs
> +    fn ffw_stream_get_side_data(stream: *const c_void, index: c_uint) -> *mut c_void;
```suggestion
    fn ffw_stream_get_side_data(stream: *const c_void, index: usize) -> *const c_void;
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.rs
> +    ) -> c_int;
Be careful with types. C type `size_t` isn't always a 64-bit unsigned integer.
```suggestion
    fn ffw_stream_add_side_data(
        stream: *mut c_void,
        data_type: c_int,
        data: *const u8,
        size: usize,
    ) -> c_int;
```

2023-03-19 15:42 UTC, operutka commented on src/format/stream.rs
> +                data.len() as u64,
```suggestion
                data.as_ptr(),
                data.len(),
```

2023-04-12 19:30 UTC, irkill commented on src/packet.c
> +uint8_t* ffw_packet_side_data_get_data(const AVPacketSideData* side_data) {
Done.

2023-04-12 19:34 UTC, irkill commented on src/format/stream.rs
> +}
Changed the definition and moved `PacketSideDataRef` into `packet.rs`. Removed `PacketSideData`.

2023-04-12 19:35 UTC, irkill commented on src/format/stream.rs
> +}
Maybe rename  `SideDataRef` to `SideData`?

2023-04-12 19:38 UTC, irkill commented on src/packet.rs
> +    fn ffw_packet_side_data_get_data(side_data: *mut c_void) -> *mut u8;
Done.

2023-04-12 19:38 UTC, irkill commented on src/format/stream.c
> +AVPacketSideData* ffw_stream_get_side_data(const AVStream* stream, unsigned index) {
Done.

2023-04-12 19:38 UTC, irkill commented on src/format/stream.c
> +int ffw_stream_get_nb_side_data(const AVStream* stream) {
Done.

2023-04-12 19:38 UTC, irkill commented on src/format/stream.rs
> +    fn ffw_stream_get_nb_side_data(stream: *const c_void) -> c_uint;
Done.

2023-04-12 19:38 UTC, irkill commented on src/format/stream.rs
> +    fn ffw_stream_get_side_data(stream: *const c_void, index: c_uint) -> *mut c_void;
Done.

2023-04-12 19:39 UTC, irkill commented on src/format/stream.rs
> +    ) -> c_int;
Done.

2023-04-12 19:39 UTC, irkill commented on src/format/stream.rs
> +                data.len() as u64,
Done.

2023-04-16 09:37 UTC, operutka requested changes
Just one small thing. Otherwise, I'm happy with the PR. Good job.

Please, rebase it on top of the master branch. It shouldn't be difficult (`src` has been moved to `ac-ffmpeg/src` to fix build on other platforms). I'll merge it then.

2023-04-16 09:37 UTC, operutka commented on src/packet.rs
> +    pub(crate) fn from_raw_ptr<'a>(ptr: *const c_void) -> &'a Self {
```suggestion
    pub(crate) unsafe fn from_raw_ptr<'a>(ptr: *const c_void) -> &'a Self {
```

2023-04-16 09:39 UTC, operutka commented on src/format/stream.rs
> +}
Let's keep it as `SideDataRef` in case we decide to add an owned companion type in the future.

2023-04-22 17:56 UTC, irkill commented on src/format/stream.rs
> +}
Okay.

2023-04-22 17:58 UTC, irkill commented on src/packet.rs
> +    pub(crate) fn from_raw_ptr<'a>(ptr: *const c_void) -> &'a Self {
Done.

2023-04-23 09:30 UTC, operutka approved these changes
Good job! Thank you.

2023-04-23 09:31 UTC, merged