Expose codec tag
angelcam/rust-ac-ffmpeg pull request #62
Opened 2023-01-24 18:57 UTC by irkill

Hello! I'm faced with the following problem - I have the media file, this file has the video stream:
```bash
$ ffprobe video.mp4
Stream #0:0[0x1](und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 720x1280, 10774 kb/s, 29.98 fps, 29.97 tbr, 600 tbn (default)
```
When I remux this media file, the codec tag of this stream changes, from `hvc1` to `hev1`.
```bash
$ ffprobe result.mp4
Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 720x1280, 10774 kb/s, 29.98 fps, 29.97 tbr, 90k tbn (default)
```
And the problem is compounded by the fact that the macOS is not friendly with `hev1` codec tag.
Source media file from the example above with `hvc1` codec tag is played in macOS, but not with the `hev1` codec tag.

I think it would be great to be able to control the codec tag.

2023-01-27 14:56 UTC, operutka commented
Perfect! Thank you for the PR. Hopefully, I'll find some time next week to do a code review.

2023-03-19 14:14 UTC, operutka requested changes
Thank you again for your PR and sorry for the delay. It's a bit hard for me to find some time for pet projects. There are a few minor issues. Otherwise, I'm happy with the PR.

2023-03-19 14:14 UTC, operutka commented on src/codec/mod.rs
> +impl From<u32> for CodecTag {
If you implement also `impl From<&[u8; 4]> for CodecTag { ... }`, users will be able to set codec tags like this:
```rust
builder.codec_tag(b"hevc");
```

2023-04-09 13:32 UTC, irkill commented on src/codec/mod.rs
> +#[derive(Default, PartialEq)]
Default codec tag - 0. I think it's useful to have a `Default` here for ease of use, so that users who don't need to deal with codec tag can just choose the default value.

2023-04-09 13:33 UTC, irkill commented on src/codec/mod.rs
> +    fn ffw_codec_parameters_get_codec_tag(params: *const c_void) -> c_uint;
Done.

2023-04-09 13:34 UTC, irkill commented on src/codec/mod.rs
> +    fn ffw_codec_parameters_set_codec_tag(params: *mut c_void, codec_tag: c_uint);
Done.

2023-04-09 13:34 UTC, irkill commented on src/codec/mod.rs
> +    fn ffw_encoder_set_codec_tag(encoder: *mut c_void, codec_tag: c_uint);
Done.

2023-04-09 13:44 UTC, irkill commented on src/codec/mod.rs
> +impl From<u32> for CodecTag {
Done.

2023-04-14 18:07 UTC, irkill commented on src/codec/mod.rs
> +#[derive(Default, PartialEq)]
After a while, it seems that the `Default` isn't really needed yet. So I deleted the `Default`. It will be easier to add it later than to remove it.

2023-04-16 10:02 UTC, operutka approved these changes
Perfect!

2023-04-16 10:03 UTC, merged