expose input format name from demuxer
angelcam/rust-ac-ffmpeg pull request #66
Opened 2023-03-14 17:40 UTC by bavardage

It can be useful to be able to figure out what input format the demuxer ended up with, especially when doing format guessing.

In this PR I:

 - expose the input format on the demuxer
 - expose the [name](https://ffmpeg.org/doxygen/2.7/structAVInputFormat.html#a850db3eb225e22b64f3304d72134ca0c) of the input format

2023-03-14 17:40 UTC, bavardage commented
cc @operutka (I don't have permissions to request a review)

2023-03-19 13:25 UTC, operutka requested changes
Thank you for your PR. There are few changes I'd like to make before merging it. It's mostly codestyle. The biggest issue is the lifetime uncertainty of the `Demuxer::input_format()` result. However, fixing it would require additional changes that are beyond the scope of this PR. I guess it's fine the way it is for now. I'll probably change the API a bit in the future to reflect the demuxer lifetime.

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.c
> +const struct AVInputFormat* ffw_demuxer_get_input_format(Demuxer* demuxer);
```suggestion
const AVInputFormat* ffw_demuxer_get_input_format(const Demuxer* demuxer);
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.c
> +const struct AVInputFormat* ffw_demuxer_get_input_format(Demuxer* demuxer) {
```suggestion
const AVInputFormat* ffw_demuxer_get_input_format(const Demuxer* demuxer) {
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +use std::ffi::CStr;
Please, merge it with the import on line 7.

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +    fn ffw_demuxer_get_input_format(demuxer: *mut c_void) -> *mut c_void; // todo: const?
```suggestion
    fn ffw_demuxer_get_input_format(demuxer: *const c_void) -> *const c_void;
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +    fn ffw_input_format_name(input_format: *mut c_void) -> *const c_char;
```suggestion
    fn ffw_input_format_name(input_format: *const c_void) -> *const c_char;
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +
```suggestion
    pub fn input_format(&self) -> InputFormat {
        // XXX: This is potentially very ugly as we rely on the fact that the
        // input formats are statically allocated by FFmpeg and not owned by
        // demuxers (and the underlying format contexts). In future versions,
        // we should capture lifetime of the demuxer in the returned type.
        unsafe {
            InputFormat {
                ptr: ffw_demuxer_get_input_format(self.ptr) as _,
            }
        }
    }
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +    }
There is no need to clone the string.

```suggestion
    pub fn name(&self) -> &str {
        unsafe {
            CStr::from_ptr(ffw_input_format_name(self.ptr))
                .to_str()
                .expect("invalid format name")
        }
    }
```

2023-03-19 13:25 UTC, operutka commented on ac-ffmpeg/src/format/demuxer.rs
> +}
The test is potentially quite fragile as it relies on behavior of the underlying library. Imagine what would happen if you compiled your own version of FFmpeg without the MP3 format support.

I'd remove the test. There is really no need for it.

2023-03-20 13:29 UTC, bavardage commented on ac-ffmpeg/src/format/demuxer.rs
> +use std::ffi::CStr;
done

2023-03-20 13:30 UTC, bavardage commented on ac-ffmpeg/src/format/demuxer.rs
> +}
fair - wanted to make sure things were plumbed through correctly, but have removed

2023-03-20 13:32 UTC, bavardage commented
yeah, I guess mirroring demuxer lifetime would be fine, although as you say in that comment they are allocated statically and so live longer than the demuxers

2023-03-20 13:32 UTC, bavardage commented
thanks for the review - I think I've addressed everything

2023-04-16 10:36 UTC, operutka approved these changes
Good! Thank you again for your PR.

2023-04-16 10:37 UTC, merged