Implement video filtering with libavfilter
angelcam/rust-ac-ffmpeg pull request #68
Opened 2023-03-20 13:01 UTC by KingOfTheBlues

Adds bindings for libavfilter attempting to follow established patterns where possible. Audio filters to be added in later.

The implementation is based on the ffmpeg example: https://www.ffmpeg.org/doxygen/trunk/filtering_8c-source.html

Thanks in advance for your time considering this PR and providing any feedback.

2023-04-16 10:14 UTC, operutka commented
Hi @KingOfTheBlues and thank you for the PR. I've checked it just briefly and it's looking good. I'll have to find some time to look into it in detail though.

Until then, please put `avfilter` behind a feature gate. Without it, we could be breaking existing builds by introducing a new link time dependency which may not be available (especially if a custom build of FFmpeg is being used).

2023-04-23 11:41 UTC, operutka requested changes

2023-04-23 11:41 UTC, operutka commented on ac-ffmpeg/src/codec/video/filter.c
> +    return ret;
Based on the FFmpeg documentation and the example [here](http://ffmpeg.org/doxygen/5.1/filtering_video_8c-example.html#_a32), the `inputs` and `outputs` should be deallocated.

```suggestion
    if ((ret = avfilter_graph_parse_ptr(filter_graph, filters_descr, &inputs, &outputs, NULL)) < 0) {
        goto end;
    }

    if ((ret = avfilter_graph_config(filter_graph, NULL)) < 0) {
        goto end;
    }

end:
    avfilter_inout_free(&inputs);
    avfilter_inout_free(&outputs);

    return ret;
```

2023-04-23 11:41 UTC, operutka commented on ac-ffmpeg/src/codec/video/filter.c
> +    return ret;
I'm not sure if this is correct. The FFmpeg documentation does not say that `av_buffersrc_add_frame` would behave the same way as `avcodec_send_frame`. Is it possible that pushing one frame to a filter input can generate multiple frames at the filter output? Do we also have to consume all output frames before pushing the next input frame (i.e. is it possible that `av_buffersrc_add_frame` would return `AVERROR(EAGAIN)`)?

2023-04-23 11:41 UTC, operutka commented on ac-ffmpeg/src/codec/video/filter.rs
> +        }
This check probably isn't necessary.

2023-04-28 09:04 UTC, KingOfTheBlues commented
thanks so much @operutka for the awesome feedback! The code is now greatly simplified and I really appreciate the help here. I believe I have addressed all your comments now

2023-04-28 09:07 UTC, KingOfTheBlues commented on ac-ffmpeg/src/codec/video/filter.c
> +    return ret;
thought I had addressed this one, actually I reverted the change for now as applying the respective change in the C code yields "all frames must be consumed before flushing" from CodecError

2025-05-15 14:48 UTC, closed without merging